# Site settings
title: "Kamil Maślanka - Portfolio"
description: "Portfolio of Unity and game development projects."
baseurl: ""      # leave empty for GitHub Pages at username.github.io
url: "https://juna8001.github.io"  # replace with your URL

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Collections / directories
collections:
  projects:
    output: true

defaults:
  - scope:
      type: "projects"
    values:
      layout: "project"   # optional: auto-assign layout to all project pages
      
# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Theme
theme: minima
# remote_theme: "jekyll/minima@1e8a445"

minima:
  skin: dark
  nav_pages:
    - index.md
    - about.md
    - blog.md
